"""Curated language resources for contextual sentence completion.

The Sign Language Studio translates recognised signs into partial English
text.  Users of that workflow type (or sign) very short, high-frequency
phrases, so the completion model does not need a statistical giant: it needs
a compact, high-precision language resource that runs locally, offline and
instantly.

Two complementary resources live here:

``PHRASE_BANK``
    Hand-ranked ``context -> continuation`` entries.  Keys are *normalised*
    contexts (lower case, apostrophes removed, e.g. ``"i want to"``) and
    values are natural continuations ordered by how common they are.  This is
    the high-confidence source used for the well-known frames such as
    ``"I need"``, ``"Can you"`` or ``"Where is"``.

``PHRASE_CORPUS``
    Complete, grammatical sentences used for (a) phrase-level completion of
    contexts that are not in the bank and (b) a bigram/trigram back-off model
    that predicts the *next word* when no phrase continuation is known.
"""

from typing import Dict, List

# ---------------------------------------------------------------------------
# Context -> ranked continuations (the precision layer)
# ---------------------------------------------------------------------------

PHRASE_BANK: Dict[str, List[str]] = {
    "i": [
        "need help", "want to go home", "am sorry", "am fine", "don't know",
        "love you", "understand", "am hungry", "need water", "feel tired",
        "am going home", "have a question", "am thirsty", "am not sure",
        "can help you", "would like some water", "am learning sign language",
        "am tired", "miss you", "am ready", "am deaf", "use sign language",
    ],
    "i am": [
        "going home", "going to school", "going outside", "fine", "sorry",
        "hungry", "thirsty", "tired", "happy", "ready", "not sure", "here",
        "a student", "going to bed", "not feeling well", "learning sign language",
        "busy right now", "in pain", "deaf", "from India", "very happy today",
        "going to the doctor", "cooking dinner", "almost done", "practicing my signs",
    ],
    "i am going": [
        "home", "to school", "outside", "to bed", "to the doctor",
        "to the market", "now", "with you", "home now",
    ],
    "i am going to": [
        "school", "the market", "bed", "the doctor", "my friend's house",
        "finish this", "sleep early",
    ],
    "i am not": ["sure", "feeling well", "ready", "going today", "happy about this"],
    "i am almost": ["done", "finished", "ready"],
    "i need": [
        "help", "some water", "to go home", "a doctor", "more time", "to rest",
        "help please", "my medicine", "to sit down", "something to eat",
        "to use the bathroom", "a break", "your help", "an interpreter",
        "to take my medicine", "my glasses", "a wheelchair",
    ],
    "i need to": [
        "go home", "use the bathroom", "see a doctor", "eat something",
        "rest now", "leave early", "call my mother", "take my medicine",
        "sit down", "ask you something",
    ],
    "i want": [
        "to go home", "to eat something", "some water", "to talk to you",
        "to rest now", "help", "to learn sign language", "to go outside",
        "to sleep", "to see a doctor", "a cup of tea", "to practice more",
        "to go to school", "to drink water",
    ],
    "i want to": [
        "go home", "talk to you", "eat something", "learn more", "rest now",
        "see a doctor", "drink water", "go outside", "go to school", "help you",
        "know more", "come with you", "take a break", "say something",
        "practice sign language", "go to bed",
    ],
    "i would": [
        "like some water", "like to go home", "like a cup of tea",
        "like to rest now", "like help please", "like to learn more",
        "like to talk to you", "like something to eat",
    ],
    "i would like": [
        "some water", "to go home", "a cup of tea", "to rest now", "help please",
        "to learn sign language", "to talk to you", "something to eat",
        "to see a doctor", "more time please",
    ],
    "i have": [
        "a question", "a headache", "to go now", "no money", "a meeting today",
        "two children", "to take my medicine", "a fever", "a cough",
        "finished my work", "an appointment",
    ],
    "i have a": ["question", "headache", "fever", "cough", "meeting today"],
    "i have to": ["go now", "study", "work today", "leave early", "take my medicine"],
    "i feel": [
        "tired", "sick", "better today", "cold", "hungry", "dizzy",
        "worried about you", "pain in my hand", "fine", "much better",
    ],
    "i think": [
        "so", "you are right", "we should go", "it is fine",
        "that is a good idea", "I need help",
    ],
    "i dont": [
        "know", "understand", "feel well", "want to go", "have time",
        "like that", "speak English", "need it", "agree with you",
    ],
    "i dont understand": ["please repeat", "the question", "can you sign slowly?"],
    "i did not": ["understand", "hear you", "see that"],
    "i can": ["help you", "wait", "sign a little", "do it", "come with you", "drive you home"],
    "i cant": [
        "hear you", "find my phone", "go today", "remember", "move my hand",
        "stay long", "do it alone", "understand the question", "open the door",
    ],
    "i will": ["help you", "be there soon", "call you later", "wait here", "try my best", "be right back"],
    "i will be": ["there soon", "right back", "late today", "waiting here"],
    "i was": ["tired", "at home", "in class", "very happy", "busy"],
    "i went": ["home", "to the doctor", "to school", "to the market", "to bed early"],
    "i hope": ["you feel better", "to see you soon", "that helps", "it works"],
    "i like": ["coffee", "tea", "your idea", "sign language", "to read books", "this place", "spicy food"],
    "i love": ["you", "this", "my family", "sign language", "reading books", "tea"],
    "i use": ["sign language", "a wheelchair", "hearing aids"],
    "i read": ["lips", "books every day", "the news"],
    "i agree": ["with you", "completely", "with that idea"],
    "im": [
        "sorry", "hungry", "tired", "fine", "not sure", "going home now",
        "learning sign language", "a student", "ready", "thirsty",
    ],
    "can": [
        "you help me?", "you come here?", "you call me?", "I help you?",
        "you wait a moment?", "you repeat that?", "you sign slowly?",
        "I have some water?", "you hear me?", "I sit here?",
    ],
    "can you": [
        "help me?", "come here?", "call me?", "wait a moment?", "repeat that?",
        "sign slowly?", "open the door?", "bring me some water?",
        "turn on the light?", "help me with this?", "say it again?", "hear me?",
        "drive me home?", "pick me up?", "write it down?",
    ],
    "can i": [
        "help you?", "have some water?", "sit here?", "use your phone?",
        "go now?", "ask a question?", "come with you?", "borrow your pen?",
        "open the window?", "take a photo?",
    ],
    "where": [
        "is the bathroom?", "are you?", "is my phone?", "is the hospital?",
        "is the exit?", "are my keys?", "do you live?", "is the doctor?",
        "are we going?", "can I find water?",
    ],
    "where is": [
        "the bathroom?", "my phone?", "the hospital?", "the doctor?", "the exit?",
        "my bag?", "your teacher?", "the water?", "the office?", "the kitchen?",
        "the station?", "the nearest bus stop?", "your house?", "my book?",
    ],
    "where are": ["you?", "we going?", "my keys?", "the children?", "you from?"],
    "what": [
        "is your name?", "time is it?", "do you want?", "is the matter?",
        "are you doing?", "day is today?", "happened?", "do you mean?",
        "can I do for you?", "is that?",
    ],
    "what is": ["your name?", "the matter?", "that?", "the time?", "your phone number?", "happening?"],
    "what time": ["is it?", "does the class start?", "should we meet?", "do you finish work?"],
    "when": [
        "are you coming?", "does the class start?", "will you be home?",
        "do we leave?", "can we go?", "is the meeting?",
    ],
    "who": ["are you?", "is that?", "can help me?", "is your teacher?", "is coming with us?"],
    "why": ["are you late?", "are you sad?", "did you do that?", "is it closed?", "not?"],
    "how": [
        "are you?", "do I get to the station?", "much does it cost?",
        "long will it take?", "old are you?", "can I help?", "do I turn this on?",
    ],
    "how are": ["you?", "you feeling today?", "things going?", "we going to get there?"],
    "how much": ["does it cost?", "time do we have?", "water should I drink?"],
    "how do": ["I get to the station?", "I turn this on?", "I say this in sign language?", "you feel today?"],
    "do you": [
        "understand me?", "speak English?", "know sign language?", "need help?",
        "have time?", "want some water?", "like coffee?", "live nearby?",
        "have an interpreter?", "want to go home?",
    ],
    "do you have": ["time?", "an interpreter?", "my phone?", "a pen?", "some water?"],
    "are you": [
        "okay?", "hungry?", "coming?", "busy?", "tired?", "ready?", "a doctor?",
        "my teacher?", "sure?", "free tomorrow?",
    ],
    "is it": ["okay?", "time to go?", "far from here?", "cold outside?", "ready?", "safe?", "your book?", "open now?"],
    "lets": [
        "go home", "eat something", "take a break", "practice sign language",
        "go outside", "start now", "talk later", "meet tomorrow", "try again",
    ],
    "let me": ["help you", "know", "try", "check", "think", "see", "call the doctor"],
    "may i": ["come in?", "ask a question?", "use the bathroom?", "sit here?", "have some water?"],
    "please": [
        "help me", "wait here", "come here", "sign slowly", "repeat that",
        "give me some water", "turn on the light", "speak slowly", "be careful",
        "write it down",
    ],
    "please help": ["me", "me stand up", "me find my phone", "me with this", "me call a doctor"],
    "please sign": ["slowly", "again", "more slowly please"],
    "thank": ["you", "you very much", "you for your help", "you so much", "you for waiting"],
    "thank you": ["very much", "for your help", "so much", "for helping me", "for everything", "for waiting"],
    "good": ["morning", "afternoon", "evening", "night", "idea", "luck", "to see you", "morning, how are you?"],
    "good morning": [", everyone", ", teacher", ", how are you?"],
    "nice to": ["meet you", "see you again", "talk to you", "meet you all"],
    "see you": ["tomorrow", "later", "soon", "next week", "at school", "in class"],
    "excuse": ["me", "me, where is the bathroom?", "me, I need help", "me, can you help me?"],
    "hello": [", how are you?", "my friend", "everyone", "nice to meet you", "again"],
    "hi": [", how are you?", "there", "everyone", "nice to meet you"],
    "yes": ["please", ", I agree", ", of course", ", that is fine", ", thank you", ", I understand"],
    "no": [", thank you", "problem", ", I don't think so", "worries"],
    "help": ["me please", "me", "me find my phone", "me stand up"],
    "sorry": [", I am late", "about that", ", I did not understand", ", for the delay"],
    "my name": ["is Alex", "is Priya", "is Sam"],
    "my name is": ["Alex", "Priya", "Sam"],
    "this is": ["my friend", "my mother", "my teacher", "important", "my phone number", "a mistake"],
    "that is": ["fine", "correct", "a good idea", "my bag", "not right", "very kind of you"],
    "it is": ["okay", "fine", "time to go", "very cold today", "not working", "my book", "too late", "too noisy here"],
    "its": ["okay", "fine", "time to go", "cold in here", "not working", "my book"],
    "you are": ["welcome", "right", "my friend", "very kind", "late", "doing great"],
    "we are": ["going home", "ready", "here to help", "almost done", "learning sign language"],
    "we need": ["help", "more time", "to leave now", "a doctor", "water"],
    "there is": ["a problem", "someone at the door", "no signal", "a meeting today", "water on the floor"],
    "he is": ["my brother", "not here", "a doctor", "coming soon", "sleeping"],
    "she is": ["my sister", "a teacher", "not here", "coming soon", "my friend"],
    "they are": ["coming now", "my friends", "outside", "not here"],
    "have a": ["good day", "nice day", "safe trip", "great weekend", "good time"],
    "take": ["care", "your time", "a seat", "this medicine", "a break"],
    "come": ["here please", "with me", "in please", "back soon"],
    "go": ["home now", "straight ahead", "left at the corner", "inside please"],
    "turn": ["on the light", "off the fan", "left at the corner", "right at the light"],
    "turn on": ["the light", "the fan", "the TV", "the computer"],
    "turn off": ["the fan", "the light", "the TV", "the computer"],
    "open": ["the door please", "the window please", "your book", "the box"],
    "close": ["the door please", "the window please", "your book", "the box"],
    "wait": ["a moment please", "for me", "here please", "a second"],
    "wait for": ["me please", "a moment", "the doctor"],
    "stop": ["please", "the car", "talking"],
    "be": ["careful", "quiet please", "patient"],
    "call": ["the doctor", "my mother", "the police", "an ambulance", "me later", "a taxi"],
    "just a": ["moment please", "second please", "minute please"],
    "everything is": ["fine", "okay", "ready"],
    "nothing is": ["wrong", "broken", "missing"],
    "the light": ["is too bright", "is not working", "is on"],
    "my hand": ["hurts", "is tired", "is fine now"],
    "repeat": ["that please", "it slowly please", "the question please"],
    "i am deaf": ["please face me when you speak", "I use sign language", "please write it down"],
}

# ---------------------------------------------------------------------------
# Complete sentences: phrase-level coverage + n-gram statistics
# ---------------------------------------------------------------------------

PHRASE_CORPUS = [
    # Greetings and politeness
    "Hello, how are you?",
    "Hello, my name is Alex.",
    "Hello, nice to meet you.",
    "Hi, how are you?",
    "Hi, nice to meet you.",
    "Good morning, everyone.",
    "Good morning, how are you?",
    "Good afternoon, teacher.",
    "Good evening, how are you?",
    "Good night, see you tomorrow.",
    "Goodbye, take care.",
    "Goodbye, have a nice day.",
    "See you later.",
    "See you tomorrow.",
    "See you soon.",
    "See you next week.",
    "Nice to meet you.",
    "Nice to see you again.",
    "Thank you.",
    "Thank you very much.",
    "Thank you for your help.",
    "Thank you for helping me.",
    "Thank you for waiting.",
    "Thanks a lot.",
    "You are welcome.",
    "Please help me.",
    "Excuse me.",
    "Excuse me, where is the bathroom?",
    "Excuse me, can you help me?",
    "I am sorry.",
    "Sorry, I am late.",
    "Sorry, I did not understand.",
    "Sorry about that.",
    "No problem.",
    "It is okay.",
    "It was nice talking to you.",
    "Have a good day.",
    "Have a nice day.",
    "Take care.",
    "Wait a moment please.",
    "Please wait here.",
    "Please come here.",
    "Please sign slowly.",
    "Please repeat that.",
    "Please speak slowly.",
    "Please write it down.",
    "Please face me when you speak.",
    # Needs and requests
    "I need help.",
    "I need help please.",
    "I need some water.",
    "I need to go home.",
    "I need a doctor.",
    "I need my medicine.",
    "I need more time.",
    "I need to rest.",
    "I need to sit down.",
    "I need to use the bathroom.",
    "I need something to eat.",
    "I need a break.",
    "I need your help.",
    "I need to call my mother.",
    "I need my glasses.",
    "I need a wheelchair.",
    "I need to take my medicine.",
    "I need an interpreter.",
    "I want to go home.",
    "I want to eat something.",
    "I want some water.",
    "I want to talk to you.",
    "I want to rest now.",
    "I want to learn sign language.",
    "I want to see a doctor.",
    "I want to go outside.",
    "I want to sleep.",
    "I want to go to school.",
    "I want a cup of tea.",
    "I want to drink water.",
    "I want to practice more.",
    "I would like some water.",
    "I would like to go home.",
    "I would like a cup of tea.",
    "I would like to rest now.",
    "I would like help please.",
    "I would like to learn more.",
    "I would like something to eat.",
    "I would like to talk to you.",
    "Please give me some water.",
    "Please call a doctor.",
    "Please call an ambulance.",
    "Please call the police.",
    "Please open the door.",
    "Please close the window.",
    "Please turn on the light.",
    "Please turn off the fan.",
    "Please help me stand up.",
    "Please help me find my phone.",
    "Please bring me my bag.",
    "Please repeat the question.",
    "Please speak one at a time.",
    # Questions
    "Where is the bathroom?",
    "Where is my phone?",
    "Where is the hospital?",
    "Where is the doctor?",
    "Where is the exit?",
    "Where is the station?",
    "Where is my bag?",
    "Where is the nearest bus stop?",
    "Where is your teacher?",
    "Where is the kitchen?",
    "Where are you?",
    "Where are my keys?",
    "Where are we going?",
    "Where do you live?",
    "Can you help me?",
    "Can you come here?",
    "Can you call me?",
    "Can you wait a moment?",
    "Can you repeat that?",
    "Can you sign slowly?",
    "Can you open the door?",
    "Can you hear me?",
    "Can you drive me home?",
    "Can you bring me water?",
    "Can you write it down?",
    "Can you say it again?",
    "Can I help you?",
    "Can I have some water?",
    "Can I sit here?",
    "Can I use your phone?",
    "Can I ask a question?",
    "Can I go now?",
    "Do you understand me?",
    "Do you speak English?",
    "Do you know sign language?",
    "Do you need help?",
    "Do you want some water?",
    "Do you have time?",
    "Do you have an interpreter?",
    "Do you live nearby?",
    "Do you like coffee?",
    "Are you okay?",
    "Are you hungry?",
    "Are you coming?",
    "Are you busy?",
    "Are you tired?",
    "Are you ready?",
    "Are you a doctor?",
    "Are you my teacher?",
    "What is your name?",
    "What time is it?",
    "What do you want?",
    "What is the matter?",
    "What are you doing?",
    "What happened?",
    "What do you mean?",
    "What can I do for you?",
    "What day is today?",
    "When are you coming?",
    "When does the class start?",
    "When will you be home?",
    "When do we leave?",
    "Who are you?",
    "Who is that?",
    "Who can help me?",
    "Why are you late?",
    "Why are you sad?",
    "How are you?",
    "How are you feeling today?",
    "How much does it cost?",
    "How long will it take?",
    "How do I get to the station?",
    "How do I turn this on?",
    "How old are you?",
    "Is it okay?",
    "Is it time to go?",
    "Is it far from here?",
    "Is it cold outside?",
    "May I come in?",
    "May I ask a question?",
    "May I use the bathroom?",
    # About myself
    "I am fine.",
    "I am sorry.",
    "I am hungry.",
    "I am thirsty.",
    "I am tired.",
    "I am happy.",
    "I am sad.",
    "I am cold.",
    "I am ready.",
    "I am here.",
    "I am going home.",
    "I am going to school.",
    "I am going outside.",
    "I am going to bed.",
    "I am going to the doctor.",
    "I am going to the market.",
    "I am a student.",
    "I am learning sign language.",
    "I am not sure.",
    "I am not feeling well.",
    "I am busy right now.",
    "I am very happy today.",
    "I am in pain.",
    "I am dizzy.",
    "I am from India.",
    "I am deaf.",
    "I am almost done.",
    "I am cooking dinner.",
    "I am watching a movie.",
    "I am reading a book.",
    "I am working today.",
    "I am studying English.",
    "I am practicing my signs.",
    "I feel tired.",
    "I feel sick.",
    "I feel better today.",
    "I feel cold.",
    "I feel pain in my hand.",
    "I feel worried about you.",
    "I have a question.",
    "I have a headache.",
    "I have a fever.",
    "I have a cough.",
    "I have to go now.",
    "I have no money.",
    "I have a meeting today.",
    "I have two children.",
    "I have to take my medicine.",
    "I have to leave now.",
    "I think so.",
    "I think you are right.",
    "I think we should go.",
    "I don't know.",
    "I don't understand.",
    "I don't feel well.",
    "I don't want to go.",
    "I don't have time.",
    "I don't like that.",
    "I don't speak English.",
    "I did not understand the question.",
    "I can help you.",
    "I can wait.",
    "I can sign a little.",
    "I can't hear you.",
    "I can't find my phone.",
    "I can't go today.",
    "I can't remember.",
    "I can't move my hand.",
    "I understand.",
    "I agree with you.",
    "I love you.",
    "I miss you.",
    "I like coffee.",
    "I like tea.",
    "I like your idea.",
    "I like sign language.",
    "I like to read books.",
    "I will help you.",
    "I will be there soon.",
    "I will call you later.",
    "I will wait here.",
    "I will try my best.",
    "I will be right back.",
    "I was tired.",
    "I was at home.",
    "I was in class.",
    "I went home.",
    "I went to the doctor.",
    "I went to school today.",
    "I hope you feel better.",
    "I hope to see you soon.",
    "I use sign language.",
    "I read lips.",
    "My hand hurts.",
    "My back hurts.",
    # People, places and everyday sentences
    "My name is Alex.",
    "My name is Priya.",
    "My name is Sam.",
    "This is my friend.",
    "This is my mother.",
    "This is my teacher.",
    "This is my phone number.",
    "This is important.",
    "That is a good idea.",
    "That is correct.",
    "That is my bag.",
    "It is time to go.",
    "It is very cold today.",
    "It is not working.",
    "It is too noisy here.",
    "Let's go home.",
    "Let's eat something.",
    "Let's take a break.",
    "Let's practice sign language.",
    "Let's go outside.",
    "Let's meet tomorrow.",
    "Let's start now.",
    "Let me help you.",
    "Let me try.",
    "Let me check.",
    "Let me know.",
    "We need help.",
    "We need more time.",
    "We are going home.",
    "We are ready.",
    "There is a problem.",
    "There is someone at the door.",
    "He is my brother.",
    "She is my sister.",
    "They are coming now.",
    "You are my friend.",
    "You are right.",
    "You are doing great.",
    "Be careful.",
    "Be quiet please.",
    "Come with me.",
    "Come here please.",
    "Go straight ahead.",
    "Turn left at the corner.",
    "Turn right at the light.",
    "Stop please.",
    "Take your time.",
    "Take this medicine.",
    "Open your book.",
    "Close the door please.",
    "Turn on the light.",
    "Turn off the fan.",
    "Wait for me please.",
    "Just a moment please.",
    "Everything is fine.",
    "Nothing is wrong.",
    "The light is too bright.",
    "I have to leave now.",
    "Call the doctor please.",
    "Call an ambulance please.",
]

# Words that cannot end a *complete* suggestion.  A continuation that stops on
# an article, possessive, preposition, conjunction or auxiliary is a fragment
# ("Where is the", "I want to") rather than a phrase.  Personal pronouns are
# deliberately allowed: "Can you help me?" and "How are you?" are complete.
FRAGMENT_ENDINGS = frozenset({
    "the", "a", "an", "of", "to", "in", "on", "at", "for", "with", "from",
    "by", "into", "onto", "over", "under", "and", "or", "but", "if", "than",
    "then", "as", "is", "are", "was", "were", "am", "be", "been", "being",
    "do", "does", "did", "will", "can", "could", "would", "should", "have",
    "has", "had", "my", "your", "his", "her", "our", "their", "this", "that",
    "these", "those",
})
