from enum import Enum

class GestureType(Enum):
    NONE = "NONE"
    ONE_FINGER = "ONE_FINGER"
    TWO_FINGER = "TWO_FINGER"
    THREE_FINGER = "THREE_FINGER"
    FOUR_FINGER = "FOUR_FINGER"
    FIVE_FINGER = "FIVE_FINGER"
    CLOSED_FIST = "CLOSED_FIST"

class InteractionState(Enum):
    IDLE = "IDLE"
    ONE_FINGER = "ONE_FINGER"
    DWELLING = "DWELLING"
    SELECTED = "SELECTED"
    CANCELLED = "CANCELLED"
    COMMITTING = "COMMITTING"